name: generate documentation

on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: dropbar # Output vimdoc project name (required)
          pandoc: "README.md" # Input pandoc file
          treesitter: true # Use treesitter for highlighting codeblocks
          demojify: true # Strip emojis from the vimdoc
          # version: "NVIM v0.8.0" # Vim version number
          # toc: true # Table of contents
          # description: "" # Project Description
          # dedupsubheadings: true # Add heading to subheading anchor links to ensure that subheadings are unique
          # ignorerawblocks: true # Ignore raw html blocks in markdown when converting to vimdoc
          # docmapping: false # Use h4 headers as mapping docs
          # docmappingprojectname: true # Use project name in tag when writing mapping docs
          # shiftheadinglevelby: 0 # Shift heading levels by specified number
          # incrementheadinglevelby: 0 # Increment heading levels by specified number
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate vimdoc"
          file_pattern: doc/*.txt
